/**
 * Differential test: this package's date layer vs. @js-temporal/polyfill.
 *
 * The polyfill is a devDependency kept solely as an executable oracle. It is never
 * bundled. Sweeping tens of thousands of dates turns "did I get month-end clamping
 * and dayOfWeek numbering right?" from a code-review judgement into a proof.
 *
 * Assertions are accumulated and checked once at the end rather than called per
 * comparison — several hundred thousand expect() calls would dominate the runtime.
 */
import { describe, it, expect } from 'vitest';
import { Temporal } from '@js-temporal/polyfill';
import {
    parseLocalDate, addDaysToString, addMonths, addYears, getWeekRange, getMonthRange,
} from './temporal.js';

/**
 * Each sweep compares tens of thousands of dates against the oracle, so these are
 * seconds-long by design: ~9s plain, ~34s under coverage instrumentation. The default
 * 5s budget fitted only by luck and broke the moment coverage was enabled, so the budget
 * is stated explicitly with enough headroom to survive a contended CI runner.
 */
const SWEEP_TIMEOUT_MS = 120_000;

const START_YEAR = 2000;
const END_YEAR = 2050;

/** Every date in [START_YEAR, END_YEAR], generated by the oracle so the sweep itself is trusted. */
function sweepDates(stepDays = 1) {
    const dates = [];
    let d = Temporal.PlainDate.from({ year: START_YEAR, month: 1, day: 1 });
    const end = Temporal.PlainDate.from({ year: END_YEAR, month: 12, day: 31 });
    while (Temporal.PlainDate.compare(d, end) <= 0) {
        dates.push(d.toString());
        d = d.add({ days: stepDays });
    }
    return dates;
}

/** Record at most `limit` mismatches so a failure prints something readable. */
function collect(limit = 8) {
    const found = [];
    return {
        check(label, actual, expected) {
            if (actual !== expected && found.length < limit) {
                found.push(`${label}: got ${actual}, oracle says ${expected}`);
            }
        },
        get found() { return found; },
    };
}

describe('temporal vs @js-temporal/polyfill', () => {
    const daily = sweepDates(1);
    const weekly = sweepDates(7);

    it('should_match_the_oracle_for_dayOfWeek_and_daysInMonth', () => {
        const m = collect();
        for (const iso of daily) {
            const oracle = Temporal.PlainDate.from(iso);
            const actual = parseLocalDate(iso);
            m.check(`dayOfWeek ${iso}`, actual.dayOfWeek, oracle.dayOfWeek);
            m.check(`daysInMonth ${iso}`, actual.daysInMonth, oracle.daysInMonth);
            m.check(`toString ${iso}`, actual.toString(), oracle.toString());
            m.check(`year ${iso}`, actual.year, oracle.year);
            m.check(`month ${iso}`, actual.month, oracle.month);
            m.check(`day ${iso}`, actual.day, oracle.day);
        }
        expect(m.found).toEqual([]);
        expect(daily.length).toBeGreaterThan(18000);
    }, SWEEP_TIMEOUT_MS);

    it('should_match_the_oracle_for_day_arithmetic', () => {
        const m = collect();
        for (const iso of daily) {
            for (const n of [-400, -31, -1, 0, 1, 31, 400]) {
                m.check(
                    `${iso} + ${n}d`,
                    addDaysToString(iso, n),
                    Temporal.PlainDate.from(iso).add({ days: n }).toString(),
                );
            }
        }
        expect(m.found).toEqual([]);
    }, SWEEP_TIMEOUT_MS);

    it('should_match_the_oracle_for_month_arithmetic_including_clamping', () => {
        const m = collect();
        for (const iso of weekly) {
            for (const n of [-13, -12, -6, -1, 0, 1, 2, 12, 13, 25]) {
                m.check(
                    `${iso} + ${n}mo`,
                    addMonths(iso, n),
                    Temporal.PlainDate.from(iso).add({ months: n }).toString(),
                );
            }
        }
        expect(m.found).toEqual([]);
    }, SWEEP_TIMEOUT_MS);

    it('should_match_the_oracle_for_month_ends_specifically', () => {
        // The clamping cases, sampled densely: naive arithmetic only diverges here.
        const m = collect();
        for (let year = START_YEAR; year <= END_YEAR; year++) {
            for (let month = 1; month <= 12; month++) {
                const last = Temporal.PlainDate.from({ year, month, day: 1 }).daysInMonth;
                for (const day of [1, 28, 29, 30, 31].filter((d) => d <= last)) {
                    const iso = Temporal.PlainDate.from({ year, month, day }).toString();
                    for (const n of [-12, -6, -1, 1, 6, 12]) {
                        m.check(
                            `${iso} + ${n}mo`,
                            addMonths(iso, n),
                            Temporal.PlainDate.from(iso).add({ months: n }).toString(),
                        );
                    }
                    m.check(
                        `${iso} + 1y`,
                        addYears(iso, 1),
                        Temporal.PlainDate.from(iso).add({ years: 1 }).toString(),
                    );
                }
            }
        }
        expect(m.found).toEqual([]);
    }, SWEEP_TIMEOUT_MS);

    it('should_match_the_oracle_for_week_ranges', () => {
        const m = collect();
        for (const iso of daily) {
            const oracle = Temporal.PlainDate.from(iso);
            const start = oracle.subtract({ days: oracle.dayOfWeek % 7 });
            const range = getWeekRange(iso);
            m.check(`weekStart ${iso}`, range.start, start.toString());
            m.check(`weekEnd ${iso}`, range.end, start.add({ days: 6 }).toString());
        }
        expect(m.found).toEqual([]);
    }, SWEEP_TIMEOUT_MS);

    it('should_match_the_oracle_for_month_ranges', () => {
        const m = collect();
        for (let year = START_YEAR; year <= END_YEAR; year++) {
            for (let month = 1; month <= 12; month++) {
                const first = Temporal.PlainDate.from({ year, month, day: 1 });
                const range = getMonthRange(year, month);
                m.check(`monthStart ${year}-${month}`, range.start, first.toString());
                m.check(
                    `monthEnd ${year}-${month}`,
                    range.end,
                    first.with({ day: first.daysInMonth }).toString(),
                );
                m.check(`daysInMonth ${year}-${month}`, range.daysInMonth, first.daysInMonth);
            }
        }
        expect(m.found).toEqual([]);
    }, SWEEP_TIMEOUT_MS);
});
